name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-eval-script-0-to-400:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eval.py script
        run: |
          python eval.py --start_count 0 --end_count 400
      - name: Upload eval logs
        uses: actions/upload-artifact@v4
        with:
          name: eval-logs1
          path: eval_logs/
  
  run-eval-script-400-to-800:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eval.py script
        run: |
          python eval.py --start_count 400 --end_count 800
      - name: Upload eval logs
        uses: actions/upload-artifact@v4
        with:
          name: eval-logs2
          path: eval_logs/
    
  run-eval-script-800-to-1200:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eval.py script
        run: |
          python eval.py --start_count 800 --end_count 1200
      
      - name: Upload eval logs
        uses: actions/upload-artifact@v4
        with: 
          name: eval-logs3
          path: eval_logs/

  run-eval-script-1200-to-1600:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eval.py script
        run: |
          python eval.py --start_count 1200 --end_count 1600
      
      - name: Upload eval logs
        uses: actions/upload-artifact@v4
        with: 
          name: eval-logs4
          path: eval_logs/

  run-eval-script-1600-to-2000:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eval.py script
        run: |
          python eval.py --start_count 1600 --end_count 2000
      
      - name: Upload eval logs
        uses: actions/upload-artifact@v4
        with: 
          name: eval-logs5
          path: eval_logs/


  run-eval-script-2000-to-2100:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eval.py script
        run: |
          python eval.py --start_count 2000 --end_count 2100
      
      - name: Upload eval logs
        uses: actions/upload-artifact@v4
        with: 
          name: eval-logssmall
          path: eval_logs/